from enum import Enum

class TagEnum(Enum):
  MUSIQUE = "MUSIQUE"
  SPORT = "SPORT"
  JEUX_VIDEOS = "JEUX_VIDEOS"
  VOYAGES = "VOYAGES"
  CINEMA = "CINEMA"
  VEGAN = "VEGAN"
  PIERCING = "PIERCING"
  TATOO = "TATOO"
