version: '3.8'

services:
  fastapi-backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:latest
    env_file: .env
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      PMA_HOST: mysql-db
    ports:
      - "8080:80"
    depends_on:
      - mysql-db
